### ISSUE TITLE
subscribe() callback not working 

### ISSUE THREAD

**Issue by ravillarreal** [theY4Kman/dcrf-client#18]
I have this code in a VueJS project:

`
this.subscription = dcrf.subscribe("projects", 1, (project, action) => {
    if (action === "update") {
      console.info("Project 1 was updated:", project);
    } else if (action === "delete") {
      console.info("Project 1 was deleted!");
    }
  });
`

But console doesnt return anything when changes are made to the Project's Model (trough Django admin)

And the connection is made and it returns data in the Network's Tab whenever i made a change

![image](https://user-images.githubusercontent.com/29802906/115169806-164e5f80-a08d-11eb-908c-5f4a91fa649e.png)

But i cant use that data inside my Vue because it dont triggers the callback function

**Comment by jhillacre** [comment]
are the `request_id`'s matching? That's how the dispatcher knows which method to call when messages come back.

For your reference, these following three messages from my server are able to trigger the callback in my own dcrf-client Vue app.

⬆ subscribe request
```json
{
  "stream": "employee",
  "payload": {
    "action": "subscribe_instance",
    "request_id": "8b15647d-0a9c-4b69-8619-f4b7de6679b1",
    "pk": 2
  }
}
```

⬇ subscribe response
```json
{
  "stream": "employee",
  "payload": {
    "errors": [],
    "data": null,
    "action": "subscribe_instance",
    "response_status": 201,
    "request_id": "8b15647d-0a9c-4b69-8619-f4b7de6679b1"
  }
}
```

⬇ subscription message
```json
{
  "stream": "employee",
  "payload": {
    "errors": [],
    "data": {
      "id": 2,
      "name": "example"
    },
    "action": "update",
    "response_status": 200,
    "request_id": "8b15647d-0a9c-4b69-8619-f4b7de6679b1"
  }
}
```

**Comment by theY4Kman** [comment]
I'm going to close this, due to inactivity. If this is still an issue, leave me a comment, and I'll reopen it.
