### ISSUE TITLE
Framework does not work with default or customized id fields

### ISSUE THREAD

**Issue by befocken** [theY4Kman/dcrf-client#6]
## The problem
I just had the issue in a django project with a few defined models, some with an explicitly set primary key (`pk`), some without one (which have then the default `pk` field, which is just the auto incrementing integer field then). The corresponding serializer was just set to serialize all fields by stating `fields = "__all__"`.
I could then connect via this and the [djangochannelrestframework](https://github.com/hishnash/djangochannelsrestframework) framework and set the callback in the `subscribe` call on the client. When updating the entity related to the subscribe call, I could see in the network tab, that the update was sent correctly, but the **callback was never called**.

## The solution
After hours and hours of reading the documentation first and then crawling through the source code, I discovered that the problem was the `isMatch(payload, selector)` call in the [fifo.ts](https://github.com/theY4Kman/dcrf-client/blob/master/src/dispatchers/fifo.ts) file.  
The call **requires**, as one can see in the build of the selector
```typescript
protected static buildSubscribeSelector(stream: string, pk: number, requestId: string) {
    return {
      stream,
      payload: {
        data: {pk},
        request_id: requestId,
      },
    };
  }
```

the primary key of the entity to be named `pk`. However, apart from not mentioning that anywhere in the README file, the default name for the primary key when using the django rest framework is not `pk`, but `id`. Moreover, this is a huge inflexibility as this requires the models to be shaped in a special way, without supporting customized primary key fields.  
Therefore, I'd suggest
1. using `id` as the default name for comparing the primary key, so that it works out of the box,
2. make the name of the `id` field customizable for the developer and
3. mention all of that in the documentation/README

**Comment by befocken** [comment]
Well, and I just saw that the other issue was, though I couldn't infer that from the issue title, referring to the same problem.
Sorry for that duplicate ^^

**Comment by theY4Kman** [comment]
hah, no worries; I appreciate the great write-up :) And you did embarrass me into actually implementing the ability to configure this. It won't be as easy as `dcrf.connect('...', {pkField: 'id'})`, but it will be as easy as
```js
dcrf.connect('...', {
  buildSubscribeSelector: (stream, pk, requestId) => ({
    stream,
    payload: {
      data: {id: pk}, 
      request_id: requestId
    }
  })
})
```

btw, `pk` is not the name of the DB field, but it's always available on all Django models as a property that points to the actual primary key field (whatever it may be named).
